production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        skip_version_check: true
        safe: true

development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: unbe_dev

test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: unbe_test

proxied-appfog:
  sessions:
    default:
      hosts:
        - 127.0.0.1:10000
      database: db
      username:
      password:
