
production:
  sessions:
    default:
      uri: mongodb://ur22lq2vd797r1eq:c2daa8d5f6fe464b84ab591e1e843163@btjktpijdsrg3cgf.mongo.clvrcld.net/btjktpijdsrg3cgf
      options:
        skip_version_check: true
        safe: true


development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: unbe_dev

test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: unbe_test