<% if ENV['MONGOHQ_URL'] %>
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
<% end %>

development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: unbe_dev

test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: unbe_test