default:
  selector: "textarea#tmpContent"
  language: 'ru'
  width: 750
  height: 550
  plugins:
     - "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker"
     - "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking"
     - "save table contextmenu directionality template paste textcolor autosave"
  invalid_elements: 'script'
  toolbar: "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | media fullpage | forecolor"


small:
  selector: "textarea"
  menubar : false
  language : 'ru'
  width: 550
  height: 300
  invalid_elements: "script"
  toolbar: "undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist | link image media"
  plugins: "link image autosave"


