default:
  selector: "textarea#tmp_content"
  language: 'ru'
  height: 550
  plugins:
     - "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker"
     - "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking"
     - "save table contextmenu directionality template paste textcolor autosave"
  invalid_elements: 'script'
  toolbar: "undo redo pagebreak | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | media fullpage | forecolor"
  gecko_spellcheck: true
  relative_urls: false
  convert_urls: false
  remove_script_host: false


small:
  selector: "textarea"
  menubar : false
  language : 'ru'
  height: 300
  invalid_elements: "script"
  toolbar: "undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist | link image media"
  plugins: "link image autosave"
  gecko_spellcheck: true
  relative_urls: false
  convert_urls: false
  remove_script_host: false